trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

variables:
  PYTHONUNBUFFERED: 1
  ATEST_RETRIES: 3

  FIRST_PARTY_LABEXTENSIONS: >-
    src/ts/wxyz-core/deathbeds-wxyz-core-0.4.0.tgz
    src/ts/wxyz-datagrid/deathbeds-wxyz-datagrid-0.4.0.tgz
    src/ts/wxyz-html/deathbeds-wxyz-html-0.4.0.tgz
    src/ts/wxyz-jsonld/deathbeds-wxyz-jsonld-0.4.0.tgz
    src/ts/wxyz-json-schema-form/deathbeds-wxyz-json-schema-form-0.4.0.tgz
    src/ts/wxyz-lab/deathbeds-wxyz-lab-0.2.1.tgz
    src/ts/wxyz-svg/deathbeds-wxyz-svg-0.4.0.tgz
    src/ts/wxyz-tpl-nunjucks/deathbeds-wxyz-tpl-nunjucks-0.4.0.tgz
    src/ts/wxyz-yaml/deathbeds-wxyz-yaml-0.4.0.tgz

  THIRD_PARTY_LABEXTENSIONS: >-
    bqplot
    @jupyter-widgets/jupyterlab-manager

jobs:
  - template: ci/job.test.yml
