jobs:
- template: ci/job.lint.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.js.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.build.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.build.yml
  parameters:
    name: MacOSX
    vmImage: macos-10.13

- template: ci/job.build.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

- template: ci/job.nbtest.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.nbtest.yml
  parameters:
    name: MacOSX
    vmImage: macos-10.13

# TODO: reinstate
# - template: ci/job.nbtest.yml
#   parameters:
#     name: Windows
#     vmImage: vs2017-win2016


- template: ci/job.robot.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ci/job.robot.yml
  parameters:
    name: MacOSX
    vmImage: macos-10.13

- template: ci/job.robot.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

- template: ci/job.combine.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04


trigger: [master]

pr: [master]
