name: wxyz

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - importnb
  - ipywidgets
  - jsonpointer
  - jupyterlab >=0.35,<0.36
  - nodejs >=8.11,<9
  - pydot
  - pyld
  - python >=3.7,<3.8
  - pyyaml
