name: wxyz-demo

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - cycler
  - dask
  - dask >=0.18.2
  - dask-ml
  - distributed
  - importnb
  - ipympl
  - ipywidgets
  - jsonpointer
  - jupyterlab >=2.1.5,<3.0.0a0
  - lime
  - matplotlib
  - nodejs >=12,<13.0.0a
  - pip
  - py-xgboost
  - pyld
  - python >=3.7,<3.8
  - pyyaml
  - scikit-image
  - scikit-learn
  - scikit-mdr
  - skrebate
  - tornado
  - tpot
  - umap-learn
  - xgboost
  - pip:
      - yellowbrick
