name: wxyz-base

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - bs4
  - doit
  - importnb
  - ipywidgets
  - jupyterlab
  - nodejs >=12,!=13.*,!=15.*
  - pip
  - python
  - twine
