{% set name = "wxyz-yaml" %}
{% set version = "0.4.0" %}
{% set fname = name.replace("-", "_") ~ "-" ~ version ~ ".tar.gz" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  path: ../../dist/sdist/{{ fname }}

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install {{ fname }} --no-deps -vv'

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - wxyz-core
    - pyyaml

test:
  imports:
    - wxyz.yaml
    - wxyz.yaml.widget_yaml

about:
  home: https://github.com/deathbeds/wxyz
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR }}/../../LICENSE.txt
  summary: experimental Jupyter widgets
