parameters:
  platforms:
    - name: Linux
      vmImage: ubuntu-16.04
      activate: source activate
      condaPlatform: linux-64
  pythons:
    - name: ThreeEight
      spec: '3.8'
      lab: '2.2'
      env: wxyz-test-38
  env_create: conda --file ci/env-test.yml --quiet
  cache_epoch: '1'

jobs:
  - ${{ each platform in parameters.platforms }}:
      - ${{ each python in parameters.pythons}}:
          - job: Lint
            pool:
              vmImage: ${{ platform.vmImage }}
            variables:
              - name: CONDA_PKGS_DIRS
                value: $(Agent.BuildDirectory)/.conda-packages/
            steps:
              - template: steps.conda.yml
                parameters:
                  name: ${{ platform.name }}

              - task: Cache@2
                inputs:
                  key: 'conda | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | "${{ python.spec }}" | "${{ python.lab }}" | ci/locks/conda.test.${{ platform.condaPlatform }}-${{ python.spec }}-${{ python.lab }}.lock'
                  path: $(Agent.BuildDirectory)/.conda-packages/
                  restoreKeys: |
                    conda | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | "${{ python.spec }}" | "${{ python.lab }}"
                    conda | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | "${{ python.spec }}"
                displayName: cache conda packages

              - script: conda create --prefix ${{ python.env }} --file ci/locks/conda.test.${{ platform.condaPlatform }}-${{ python.spec }}-${{ python.lab }}.lock
                displayName: update conda environment with test dependencies

              - task: Cache@2
                inputs:
                  key: 'yarn | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | yarn.lock'
                  restoreKeys: |
                    yarn | ${{ parameters.cache_epoch }} | "$(Agent.OS)"
                    yarn | ${{ parameters.cache_epoch }}
                  path: .yarn-packages
                displayName: cache yarn packages

              - script: ${{ platform.activate }} ./${{ python.env }} && doit -n4 "lint_*" || doit "lint_*"
                displayName: check style

              - script: ${{ platform.activate }} ./${{ python.env }} && doit -n4 hash_dist
                displayName: build dists

              - script: ${{ platform.activate }} ./${{ python.env }} && doit -n4 integrity
                displayName: check repo integrity

              - publish: dist
                artifact: Dist $(Build.BuildId)
                displayName: publish artifacts for distribution
                condition: always()

              - bash: find $(Agent.BuildDirectory)/.conda-packages -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
                condition: always()
                displayName: clean conda cache
