parameters:
  platforms:
    - name: Linux
      vmImage: ubuntu-16.04
      activate: source activate
      condaPlatform: linux-64
    - name: MacOSX
      vmImage: macos-10.14
      activate: source activate
      condaPlatform: osx-64
    - name: Windows
      vmImage: vs2017-win2016
      activate: call activate
      condaPlatform: win-64
  pythons:
    - name: ThreeSix
      spec: '3.6'
      lab: '2.2'
      env: wxyz-test-36
    - name: ThreeSeven
      spec: '3.7'
      lab: '2.2'
      env: wxyz-test-37
    - name: ThreeEight
      spec: '3.8'
      lab: '2.2'
      env: wxyz-test-38
  env_create: conda --file ci/env-test.yml --quiet
  lab_ext: jupyter labextension install --debug --no-build $(FIRST_PARTY_LABEXTENSIONS) $(THIRD_PARTY_LABEXTENSIONS)
  lab_build: jupyter lab build --debug --dev-build=False --minimize=True
  cache_epoch: '0'

jobs:
  - ${{ each platform in parameters.platforms }}:
      - ${{ each python in parameters.pythons}}:
          - job: ${{ platform.name }}${{ python.name }}
            pool:
              vmImage: ${{ platform.vmImage }}
            variables:
              - name: CONDA_PKGS_DIRS
                value: $(Agent.BuildDirectory)/.conda-packages/
              # skip some things
              - name: TESTING_IN_CI
                value: '1'
            steps:
              - template: steps.conda.yml
                parameters:
                  name: ${{ platform.name }}

              - task: Cache@2
                inputs:
                  key: 'conda | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | "${{ python.spec }}" | "${{ python.lab }}" | ci/locks/conda.test.${{ platform.condaPlatform }}-${{ python.spec }}-${{ python.lab }}.lock'
                  path: $(Agent.BuildDirectory)/.conda-packages/
                  restoreKeys: |
                    conda | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | "${{ python.spec }}" | "${{ python.lab }}"
                    conda | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | "${{ python.spec }}"
                displayName: cache conda packages

              - script: conda create --prefix ${{ python.env }} --file ci/locks/conda.test.${{ platform.condaPlatform }}-${{ python.spec }}-${{ python.lab }}.lock
                displayName: update conda environment with test dependencies

              - task: Cache@2
                inputs:
                  key: 'yarn | ${{ parameters.cache_epoch }} | "$(Agent.OS)" | yarn.lock'
                  restoreKeys: |
                    yarn | ${{ parameters.cache_epoch }} | "$(Agent.OS)"
                    yarn | ${{ parameters.cache_epoch }}
                  path: .yarn-packages
                displayName: cache yarn packages

              - script: conda info && conda list --prefix ${{ python.env }}
                displayName: list conda packages and info

              - script: ${{ platform.activate }} ./${{ python.env }} && doit setup_ts
                displayName: install npm dependencies

              - script: ${{ platform.activate }} ./${{ python.env }} && doit "dist_py*"
                displayName: build python distributions

              - script: ${{ platform.activate }} ./${{ python.env }} && doit setup_py_ci
                displayName: install python wheels

              - script: ${{ platform.activate }} ./${{ python.env }} && doit nbtest
                displayName: run notebook smoke tests

              - script: ${{ platform.activate }} ./${{ python.env }} && doit ts
                displayName: build typescript

              - script: ${{ platform.activate }} ./${{ python.env }} && doit lab_extensions
                displayName: install labextensions

              - script: ${{ platform.activate }} ./${{ python.env }} && doit lab_build
                displayName: build lab

              - script: ${{ platform.activate }} ./${{ python.env }} && doit robot
                displayName: run browser tests

              - task: PublishTestResults@2
                displayName: publish browser test results
                inputs:
                  testResultsFiles: atest/output/**/xunit.xml
                  testRunTitle: 'Robot ${{ platform.name }}${{ python.name }}'
                  mergeTestResults: true
                condition: always()

              - task: PublishPipelineArtifact@0
                displayName: publish browser test output
                inputs:
                  targetPath: atest/output
                  artifactName: $(Build.BuildId) Robot $(Agent.JobStatus) ${{ platform.name }}${{ python.name }}
                condition: always()

              - bash: find .conda-packages -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
                condition: always()
                displayName: prepare for conda cache
