parameters:
  name: Linux
  vmImage: ubuntu-16.04

jobs:
  - job: Robot_${{ parameters.name }}
    dependsOn:
      - JS_Linux
    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - template: steps.conda.robot.yml
        parameters:
          name: ${{ parameters.name }}

      - template: steps.robot.yml
        parameters:
          name: ${{ parameters.name }}
