{% set name = "ipywxyz" %}
{% set version = "0.1.0" %}
{% set fname = name ~ "-" ~ version ~ ".tar.gz" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  path: ../dist/sdist/{{ fname }}

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install {{ fname }} --no-deps -vv'

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipywidgets

test:
  requires:
    - jinja2
    - jsonpointer
    - pyld
    - jupyterlab
  imports:
    - ipywxyz

about:
  home: https://github.com/deathbeds/wxyz
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR }}/../LICENSE.txt
  summary: experimental Jupyter widgets
