name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # increment to reset all caches
  CACHE_EPOCH: 0
  # python cruft
  PYTHONIOENCODING: utf-8
  PYTHONUNBUFFERED: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  # mamba cruft
  CONDA_EXE: mamba
  FORGE: Mambaforge
  FORGE_VERSION: 4.9.2-5
  FORGE_EXT: .sh 

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
        python-version: [3.8]
        include:
          - os: ubuntu
            conda-platform: linux-64
            lab: 3
            lockfile: ci/locks/conda.test.linux-64-3.8-2.2.lock
            forge-ext: .Linux-x86_64.sh
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ env.CACHE_EPOCH }}-${{ runner.conda-platform }}-build-${{ matrix.python-version }}-${{ hashFiles(matrix.lockfile) }}
          restore-keys: |
            ${{ env.CACHE_EPOCH }}-${{ runner.conda-platform }}-build-${{ matrix.python-version }}-
      - uses: conda-incubator/setup-miniconda@v2
        with:
          use-only-tar-bz2: true
          installer-url: |
            https://github.com/conda-forge/miniforge/releases/download/${{ env.FORGE_VERSION }}/${{ env.FORGE }}-${{ env.FORGE_VERSION }}-${{ matrix.miniforge }}${{ matrix.forge-ext }}
      - run: mamba info --json
      - run: mamba create -p .conda-env --file ${{ matrix.lockfile }}
      - run: mamba list
      - run: doit -n8 ts dist_py
